### ISSUE TITLE
BGEN file format

### ISSUE THREAD

**Issue by jrvanalstine** [google/nucleus#17]
I’m wanting to implement support for the bgen file format and am looking for some guidance about what would be required beyond stamping out the proto messages. Is there a general outline for adding support for other file types?

**Comment by ThomasColthurst** [comment]
Awesome!  It's not that hard to add a file format, and you already correctly identified the first step:  writing a proto message.

The only other things I would say are:
* Be sure to re-use existing proto definitions when appropriate (for example the Variant proto for the variants stored in the BGEN).  It is okay to add additional fields to those if necessary.

* It is better to send in smaller incremental pull requests rather than one giant one.  At the bare minimum, I would recommend at least one pull request for the proto changes, one for the reader, and one for the writer.  (It is also okay to contribute just a reader and not a writer.)

* Try to follow Google's C++ and Python style guides (https://google.github.io/styleguide/cppguide.html and https://google.github.io/styleguide/pyguide.html)

* For binary formats like BGEN, we generally do the parsing in C++ and have the Python rely on that.  Having the C++ reader inherit from nucleus/io/reader_base.h::Reader is encouraged but not required.  Having the Python reader inherit from genomics_reader.DispatchingGenomicsReader is required, but is also mostly boiler plate -- if you just wanted to do the C++ part, I would be happy to hook up the CLIF and Python for you.

* Tests are required.

* Feel free to ask me questions, either on this issue or directly at thomaswc@google.com.

**Comment by jrvanalstine** [comment]
Ok thanks I’ll submit a PR when I get the chance
