### ISSUE TITLE
Can't uninstall?

### ISSUE THREAD

**Issue by paradisebee** [google/nucleus#18]
I installed nucleus with:

pip install --user google-nucleus

It threw out this error as well as successfully installed message:

Building wheel for google-nucleus (setup.py) ... error
  ERROR: Complete output from command /home/user/miniconda3/envs/py2/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-80mPYb/google-nucleus/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-2P701B --python-tag cp27:
  ERROR: /home/user/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools/version.py:1: UserWarning: Module google was already imported from None, but /tmp/pip-install-80mPYb/google-nucleus is being added to sys.path
    import pkg_resources
  This package does not support wheel creation.
  ----------------------------------------
  ERROR: Failed building wheel for google-nucleus
  Running setup.py clean for google-nucleus
Failed to build google-nucleus
Installing collected packages: google-nucleus
  Running setup.py install for google-nucleus ... done
  WARNING: Could not find .egg-info directory in install record for google-nucleus from https://files.pythonhosted.org/packages/4c/98/24e36281ccae0879a94a5de17a7769fe43937622a5b57afde6c18e6671bd/google_nucleus-0.4.1.tar.gz#sha256=eaedc19ae573d27d204192ff21014bbb2fe28c85fe4e27b328cd10b299fa6871
Successfully installed google-nucleus

I could find "google" and "nucleus" directories in /home/user/.local/lib/python2.7/site-packages,
but when I do "pip list" or "pip2 list", they are not there.

Now I want to uninstall them:

pip/pip2 uninstall google
Cannot uninstall requirement google, not installed

pip/pip2 uninstall nucleus
Cannot uninstall requirement nucleus, not installed

pip/pip2 uninstall google-nucleus
Cannot uninstall requirement google-nucleus, not installed

What should I do??

**Comment by ThomasColthurst** [comment]
You can just
$ rm -rf  /home/user/.local/lib/python2.7/site-packages/{nucleus,google/protobuf}

Long story:  Nucleus uses symbolic links in an essential way, and because of that, it needs to be distributed as a tar file and not as a traditional wheel file.  That leads both to the very confusing (but irrelevant) error message from pip install, and the problems with pip list and pip uninstall.  We plan to fix those problems in the future, but we haven't been able to find any documentation about how to get pip to be more friendly to tar files, so it is slow going.
